### ISSUE TITLE
Alarm Panel modes fail to read

### ISSUE THREAD

**Issue by hanskroner** [twrecked/pyaarlo#77]
For the last few weeks I've been facing an issue where the Alarm Panels that represent the Arlo base stations within Home Assistant fail at reading their state:

```
Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:583 
Integration: Arlo Camera Support (documentation, issues) 
First occurred: 19 October 2021, 0:00:25 (15 occurrences) 
Last logged: 7:00:19

failed to read modes (v2)
job-error=TypeError Traceback (most recent call last): File "/config/custom_components/aarlo/pyaarlo/background.py", line 34, in _run_next job["callback"](**job["args"]) File "/config/custom_components/aarlo/pyaarlo/base.py", line 159, in _event_handler self.update_mode() File "/config/custom_components/aarlo/pyaarlo/base.py", line 347, in update_mode for mode in data: TypeError: 'NoneType' object is not iterable
```

When using service calls to set the Alarm Panel's mode, the Arlo Base Stations do actually change mode (verified from within the App) but the Alarm Panels in Home Assistant do not. The particular error I pasted above started happening 6 days ago, and happens each time I tried to change modes on the Panels.

Restarting Home Assistant, which will reestablish a connection to the Arlo Cloud seems to fix the problem for a while. After observing it for a while, it seems the panels get stuck most often after a change from an "armed" mode to another "armed" mode (e.g., changing to "night" while on "home").

This is on hass-aarlo v0.7.1.7 configured with:
```
aarlo:
  refresh_devices_every: 1
  stream_timeout: 90
  reconnect_every: 180
  request_timeout: 120
  db_ding_time: 10
  recent_time: 30
  last_format: '%d-%m %H:%M'
```

**Comment by twrecked** [comment]
Apologies. I haven't had much spare time to look at this stuff. Arlo just made some changes that might making debugging this stuff a little easier.

Firstly, thanks for the logs, I'll take a look.

**Comment by twrecked** [comment]
Neither of you is getting the `activeAutomations` reply I was expecting. What should happen is we send POST a request to `https://myapi.arlo.com/hmsweb/users/devices/automation/active` and we get an `activeAutomations` response back.

@m0urs Can you paste your pyaarlo.PyArlo() settings (minus any sensitive data obviously). 

@hanskroner Can you add the following to you `configuration.yaml` and send me the logs. It just needs to be around the time things stop happening.

```yaml
aarlo:
  ... your existing config
  verbose_debug: True

logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    custom_components.aarlo.binary_sensor: debug
    custom_components.aarlo.camera: debug
    custom_components.aarlo.light: debug
    custom_components.aarlo.media_player: debug
    custom_components.aarlo.sensor: debug
    custom_components.aarlo.switch: debug
    pyaarlo: debug
```
